### PR TITLE
 added code for dark mode

### PR DESCRIPTION
**Pull request by Lovegupta112**
I have added code for dark mode in this website ...

DARK MODE1
DARK2
DARK3
.

### CODE REVIEW

**Comment by nishantc7** [comment]
Why has the font weight and style changed everywhere? In the non dark mode too? You can look on the deployed version to spot the differences. @Lovegupta112

**Comment by Lovegupta112** [comment]
But I have not changed any font style and you can also see changes in GitHub.

**Comment by nishantc7** [comment]
image  
Can you fix these? @Lovegupta112   
image

**Comment by Lovegupta112** [comment]
Ok , so I have to change the font style ??

**Comment by nishantc7** [comment]
> Ok , so I have to change the font style ??

No, can you see the two texts for shop contacts etc overalapping? Why do you think that happens?

And in the second image only half the page's colour changes to black. That is the signin page

**Comment by Lovegupta112** [comment]
Actually I have tried to add the dark mode in whole page but I think that it's body is short that's why 
And text are not overlapping , i have added text-shadow on that headings bcz the color of whole Content of the website was changing from black to white in dark mode but those headings were not changing their colours so i had to add text-shadow ...

**Comment by Lovegupta112** [comment]
According to me , I have fixed the issue like font overlapping and half dark mode . Now you can see the change

iiiiid
iiiid1

**Comment by nishantc7** [comment]
> According to me , I have fixed the issue like font overlapping and half dark mode . Now you can see the change

Good work 👍

**Pull request merged**
